version: '3'
services:
  helium-taxable:
    build: .
    image: macpie/helium-taxable:latest
    container_name: helium_taxable
    tty: true
    environment:
      HT_ADDRESSES: XX,YY
      HT_START_DATE: '2021-01-01'
      HT_END_DATE: '2021-01-07'
    volumes:
      - "./reports:/opt/helium-taxable/reports"