version: '3'
services:
  helium-taxable:
    build: .
    image: macpie/helium-taxable:latest
    container_name: helium_taxable
    tty: true
    env_file: .env
    volumes:
      - ./reports:/opt/helium-taxable/reports
      - ./data:/opt/helium-taxable/data
